const stream = document.querySelector('#listing-stream');
const search = document.querySelector('#search');
const tagSearch = document.querySelector('#tag-search');
const tags = document.querySelector('#tags');
const categories = document.querySelector('#categories');
const sentinel = document.querySelector('#sentinel');
const modal = document.querySelector('#modal');
const modalContent = document.querySelector('#modal-content');
let listings = [], auctions = [], activeCategory = 'All', activeQuery = '', activeTags = [], page = 1, observer;

const safe = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const listingTags = item => Array.isArray(item.tags) ? item.tags : [item.tag].filter(Boolean);
const filtered = () => listings.filter(item => (activeCategory === 'All' || item.category === activeCategory) && `${item.title} ${item.description} ${listingTags(item).join(' ')}`.toLowerCase().includes(activeQuery.toLowerCase()) && (!activeTags.length || listingTags(item).some(tag => activeTags.includes(tag.toLowerCase()))));
const card = item => `<article class="listing"><header class="collector-head"><b>J</b><div><strong>@JohnDoe <em>CURATOR</em></strong><small>★★★★★ <i>(312)</i></small></div><time>2h ago ···</time></header><div class="listing-main"><button class="media" data-detail="${item.id}"><img src="${safe(item.image)}" alt="${safe(item.title)}"><span class="grade">${safe(item.category)}</span></button><section class="listing-copy"><h2>${safe(item.title)}</h2><div class="meta">JAMES CO. SHIPPING COMPANY</div><p><b>@JohnDoe ★★★★★ (5.0)</b><br>This is my favorite card ever!<br>Please buy more...</p><footer><button class="price" data-purchase="${item.id}">BUY ${item.price}$</button><button class="trade" data-trade="${item.id}">TRADE</button><button class="like" aria-label="Like ${safe(item.title)}">♡</button></footer></section></div></article>`;

function renderCategories() { const types = ['All', ...new Set(listings.map(item => item.category))]; categories.innerHTML = types.map(type => `<button class="${type === activeCategory ? 'active' : ''}" data-category="${safe(type)}">${safe(type)}</button>`).join(''); }
function renderTags(filter = tagSearch.value) { const match = filter.trim().replace(/#/g, '').toLowerCase(); const values = [...new Set(listings.flatMap(listingTags))].sort().filter(tag => tag.toLowerCase().includes(match)); tags.innerHTML = values.length ? values.map(tag => { const selected = activeTags.includes(tag.toLowerCase()); return `<button type="button" class="${selected ? 'active' : ''}" data-tag="${safe(tag)}" aria-pressed="${selected}">#${safe(tag)}</button>`; }).join('') : '<span class="empty-tag">No tags found.</span>'; }
function renderFeed(reset = true) { const rows = filtered(); if (reset) page = 1; stream.innerHTML = rows.slice(0, page * 4).map(card).join('') || '<p class="load-state">No collector finds match that search.</p>'; document.querySelector('#result-count').textContent = `${rows.length} listed`; sentinel.textContent = page * 4 < rows.length ? 'Scroll for more finds ↓' : 'You are all caught up.'; }
function openModal(title, copy, form) { modalContent.innerHTML = `<h2 class="modal-title">${title}</h2><p class="modal-copy">${copy}</p>${form || ''}`; modal.showModal(); }
function money(value) { return `$${Number(value).toFixed(2)}`; }
function feeCalculator(item, type) {
  const trade = type === 'trade';
  const fields = trade ? `<label>Your trade valuation<input id="buyer-value" type="number" min="0" value="${item.price}"></label><label>Other side’s valuation<input id="seller-value" type="number" min="0" value="${item.price}"></label><label>Offer note<input required id="offer-note" placeholder="Describe the item you are offering"></label>` : `<label>Item price<input id="buyer-value" type="number" min="0" value="${item.price}"></label><label>Estimated buyer tax<input id="tax" type="number" min="0" value="0"></label><label>Courier packaging cost<input id="packaging" type="number" min="0" value="0"></label>`;
  const action = trade ? 'Send trade offer & open chat' : 'Continue to purchase review';
  return `<form class="fee-calculator" data-type="${type}">${fields}<label class="check"><input id="buyer-curator" type="checkbox"> Buyer has Curator membership ($150/month)</label><label class="check"><input id="seller-curator" type="checkbox"> Seller has Curator membership ($150/month)</label><div id="fee-summary" class="fee-summary"></div><p class="policy-note">Policy draft: payments and transaction fees apply only to completed purchases. Buyers pay taxes and shipping. Courier delivery pay is the greater of $15 or 0.5% of the valuation, plus documented packaging costs. Delivery, fraud, and enforcement rules require legal review before launch.</p><button type="submit" class="transaction-submit">${action}</button></form>`;
}
function updateFeeSummary() {
  const box = document.querySelector('.fee-calculator'); if (!box) return;
  const type = box.dataset.type; const buyerValue = Number(document.querySelector('#buyer-value')?.value || 0); const sellerValue = Number(document.querySelector('#seller-value')?.value || buyerValue); const buyerRate = document.querySelector('#buyer-curator').checked ? .01 : .04; const sellerRate = document.querySelector('#seller-curator').checked ? .01 : .04; const tax = Number(document.querySelector('#tax')?.value || 0); const packaging = Number(document.querySelector('#packaging')?.value || 0); const courier = Math.max(15, buyerValue * .005) + packaging;
  document.querySelector('#fee-summary').innerHTML = type === 'trade' ? `<b>Trade valuation estimate</b><span>Buyer-side fee (${buyerRate * 100}%): ${money(buyerValue * buyerRate)}</span><span>Other-side fee (${sellerRate * 100}%): ${money(sellerValue * sellerRate)}</span><strong>Total valuation fees: ${money(buyerValue * buyerRate + sellerValue * sellerRate)}</strong>` : `<b>Purchase estimate</b><span>Buyer marketplace fee (${buyerRate * 100}%): ${money(buyerValue * buyerRate)}</span><span>Seller marketplace fee (${sellerRate * 100}%): ${money(buyerValue * sellerRate)}</span><span>Buyer tax: ${money(tax)} · Buyer shipping/courier: ${money(courier)}</span><strong>Buyer due: ${money(buyerValue + buyerValue * buyerRate + tax + courier)}</strong><strong>Seller fee: ${money(buyerValue * sellerRate)}</strong>`;
}
function setQuery(query) { activeQuery = query.trim(); search.value = activeQuery; document.querySelector('#clear-tags').hidden = !activeQuery; renderFeed(); }
function toggleTag(tag) { const value = tag.toLowerCase(); activeTags = activeTags.includes(value) ? activeTags.filter(current => current !== value) : [...activeTags, value]; renderTags(); renderFeed(); }
function activateNav(name) { document.querySelectorAll('.bottom-nav button').forEach(button => button.classList.toggle('active', button.matches(`[data-${name}]`))); }
function showAuctionHouse() { if (observer) observer.disconnect(); sentinel.hidden = true; stream.innerHTML = `<section class="auction-house"><header class="auction-head"><div><p>Live bidding</p><h1>Auction House</h1></div><p>${auctions.length} active lots</p></header><div class="auction-grid">${auctions.map(lot => `<article class="auction-card"><img src="${safe(lot.image)}" alt="${safe(lot.title)}"><div class="auction-info"><h2>${safe(lot.title)}</h2><p>${safe(lot.category)}</p><div class="auction-stats"><div>Current bid<strong>${money(lot.currentBid)}</strong></div><div>Ends in<strong>${safe(lot.ends)}</strong></div><div>${lot.bids} bids</div></div><button class="auction-bid" data-bid="${lot.id}">Place bid</button></div></article>`).join('')}</div></section>`; window.scrollTo({ top: 0, behavior: 'smooth' }); }

document.addEventListener('click', event => {
  const tag = event.target.closest('[data-tag]'); const category = event.target.closest('[data-category]'); const detail = event.target.closest('[data-detail]'); const trade = event.target.closest('[data-trade]'); const action = event.target.closest('[data-home],[data-market],[data-auction],[data-chat],[data-sell],[data-account],[data-policy]');
  if (tag) { setDiscoveryMode('tags'); toggleTag(tag.dataset.tag); }
  if (category) { activeCategory = category.dataset.category; renderCategories(); renderFeed(); }
  if (detail) { const item = listings.find(row => row.id === detail.dataset.detail); openModal(item.title, item.description, `<div class="modal-form"><button data-trade="${item.id}">Make a trade offer</button></div>`); }
  if (trade) { const item = listings.find(row => row.id === trade.dataset.trade); openModal(`Trade for ${item.title}`, 'Each side is shown its own valuation fee. Curator pricing applies only to the member’s side.', feeCalculator(item, 'trade')); updateFeeSummary(); }
  const purchase = event.target.closest('[data-purchase]'); if (purchase) { const item = listings.find(row => row.id === purchase.dataset.purchase); openModal(`Buy ${item.title}`, 'Both buyer and seller pay their own marketplace fee. Your purchase will open delivery chat for follow-up and confirmation.', feeCalculator(item, 'purchase')); updateFeeSummary(); }
  const bid = event.target.closest('[data-bid]'); if (bid) { const lot = auctions.find(row => row.id === bid.dataset.bid); openModal(`Bid on ${lot.title}`, `Current bid: ${money(lot.currentBid)}. Bids are binding only after you confirm the transaction terms.`, `<form class="modal-form"><input required type="number" min="${lot.currentBid + 1}" placeholder="Minimum bid ${lot.currentBid + 1}"><button>Place bid</button></form>`); }
  if (action?.matches('[data-sell]')) { activateNav('sell'); openModal('List an item', 'Create your collector profile to publish listings and accept trade offers.', '<form class="modal-form"><input required placeholder="Your email"><button>Join the marketplace</button></form>'); }
  if (action?.matches('[data-chat]')) { activateNav('chat'); openModal('Collector chat', 'Your conversations and trade updates will appear here once you join the marketplace.'); }
  if (action?.matches('[data-account]')) { activateNav('account'); openModal('Your collector account', 'Sign in to manage your profile, active listings, trade history, saved searches, and Curator membership.', '<form class="modal-form"><input required type="email" placeholder="Email address"><button>Sign in or create account</button></form>'); }
  if (action?.matches('[data-policy]')) openModal('Marketplace fees', 'Standard purchase fees are 4% per side. Curator members pay 1% on their own side for $150/month. Buyers pay taxes and delivery; courier pay is the greater of $15 or 0.5% of valuation, plus packaging. Transaction and delivery terms are policy drafts pending legal review.');
  if (action?.matches('[data-auction]')) { activateNav('auction'); showAuctionHouse(); }
  if (event.target.closest('.like')) { const like = event.target.closest('.like'); like.textContent = like.textContent === '♡' ? '♥' : '♡'; like.classList.toggle('liked'); }
  if (action?.matches('[data-market],[data-home]')) { activateNav(action.matches('[data-market]') ? 'market' : 'home'); sentinel.hidden = false; activeCategory = 'All'; activeTags = []; setQuery(''); renderTags(); renderCategories(); renderFeed(); if (observer) observer.observe(sentinel); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  if (event.target.matches('.close')) modal.close();
});
search.addEventListener('input', event => { setDiscoveryMode('search'); setQuery(event.target.value); });
tagSearch.addEventListener('input', event => renderTags(event.target.value));
tagSearch.addEventListener('keydown', event => { if (event.key === 'Enter') { event.preventDefault(); const requested = event.target.value.match(/#?[a-z0-9-]+/gi) || []; const available = [...new Set(listings.flatMap(listingTags))]; const matches = requested.map(value => value.replace('#', '').toLowerCase()).filter(value => available.some(tag => tag.toLowerCase() === value)); activeTags = [...new Set([...activeTags, ...matches])]; event.target.value = ''; renderTags(); renderFeed(); } });
document.querySelector('#clear-tags').addEventListener('click', () => setQuery(''));
function setDiscoveryMode(mode) { const discovery = search.closest('.discovery'); const isSearch = mode === 'search'; discovery.classList.toggle('mode-search', isSearch); discovery.classList.toggle('mode-tags', !isSearch); document.querySelector('#search-tab').classList.toggle('is-active', isSearch); document.querySelector('#tags-tab').classList.toggle('is-active', !isSearch); document.querySelector('#search-tab').setAttribute('aria-selected', String(isSearch)); document.querySelector('#tags-tab').setAttribute('aria-selected', String(!isSearch)); }
document.querySelector('#search-tab').addEventListener('click', () => { setDiscoveryMode('search'); search.focus(); });
document.querySelector('#tags-tab').addEventListener('click', () => { setDiscoveryMode('tags'); tagSearch.focus(); });
modal.addEventListener('click', event => { if (event.target === modal) modal.close(); });
document.addEventListener('submit', event => { if (event.target.closest('#modal')) { event.preventDefault(); const trade = event.target.matches('.fee-calculator[data-type="trade"]'); const purchase = event.target.matches('.fee-calculator[data-type="purchase"]'); modalContent.innerHTML = trade ? '<h2 class="modal-title">Trade offer sent.</h2><p class="modal-copy">Your offer is pending with the collector. A trade chat is now open for delivery details and follow-up.</p>' : purchase ? '<h2 class="modal-title">Purchase review saved.</h2><p class="modal-copy">Your estimate is ready. Payment and fees are collected only when a purchase is confirmed.</p>' : '<h2 class="modal-title">You’re on the list.</h2><p class="modal-copy">Thanks for your interest. Collector Marketplace will be ready for your listing or trade details soon.</p>'; } });
document.addEventListener('input', event => { if (event.target.closest('.fee-calculator')) updateFeeSummary(); });

Promise.all([fetch('data/listings.json').then(response => response.json()), fetch('data/auctions.json').then(response => response.json())]).then(([listingData, auctionData]) => { listings = listingData.sort((a, b) => a.id === 'mantle' ? -1 : b.id === 'mantle' ? 1 : 0); auctions = auctionData; renderTags(); renderCategories(); renderFeed(); observer = new IntersectionObserver(entries => { if (entries[0].isIntersecting && page * 4 < filtered().length) { page++; renderFeed(false); } }, { rootMargin: '250px' }); observer.observe(sentinel); }).catch(() => { stream.innerHTML = '<p class="load-state">The marketplace feed could not load. Please refresh the page.</p>'; });
